#!/bin/sh

##ensure: dir "dot2smali", dir "shareIO"...

APKFILE="./shareIO/EDGExample.apk"
APKNAME="EDGExample"
TARGETPKG="com"
#APKTOOLPATH="./dot2smali/tools/apktool-install-linux-r05-ibot/"
APKTOOLPATH=""

##step0
#todo: get the .apk file location
while getopts ":af:p:" optname
  do
    case "$optname" in
      "a")
        echo "Option $optname is specified"
        ;;
      "f")
        echo "Option $optname has value $OPTARG" && APKFILE="${OPTARG}"
        ;;
      "p")
        echo "Option $optname has value $OPTARG" && TARGETPKG="${OPTARG}"
        ;;
      "?")
        echo "Unknown option $OPTARG"
        ;;
      ":")
        echo "No argument value for option $OPTARG"
        ;;
      *)
      # Should not occur
        echo "Unknown error while processing options"
        ;;
    esac
  done

echo "apk-file: ${APKFILE}"

APKNAME=${APKFILE##*/}
APKNAME=${APKNAME%.*}

echo "apk-name: ${APKNAME}"


##step1
#todo: generate .dot folder, debag .apk file
#tool: androdd.py, apktool
rm ./shareIO/${APKNAME}.json

if [ ! -d "./dot2smali/input/dot/${APKNAME}" ]; then
  rm -rf ./dot2smali/input/dot/${APKNAME}
  mkdir ./dot2smali/input/dot/${APKNAME}
  python ./dot2smali/tools/androguard-1.9/androdd.py -i ${APKFILE} -o ./dot2smali/input/dot/${APKNAME} -d
else
  echo "Dir ./dot2smali/input/dot/${APKNAME} exists!"
fi

if [ ! -d "./dot2smali/input/smali/${APKNAME}" ]
then
  rm -rf ./dot2smali/input/smali/${APKNAME}
  echo "apktool path: ${APKTOOLPATH}"
  if [ -z "${APKTOOLPATH}" ]
  then
    echo "using new apktool"
    apktool d ${APKFILE} -o ./dot2smali/input/smali/${APKNAME}
  else
    echo "using old apktool"
    ${APKTOOLPATH}apktool d -f ${APKFILE} ./dot2smali/input/smali/${APKNAME}
  fi
else
  echo "Dir ./dot2smali/input/smali/${APKNAME} exists!"
fi

##step2
#todo: modify .smali files with new .dot files
#tool: dot2smali
cd dot2smali
java -jar dot2smali_fat.jar ${APKNAME} ${TARGETPKG}
cd ..

##step3
#todo: new apk srcFolder -> unsigned apk -> signed apk -> install
#tool: apktool, signapk.jar, adb
if [ -z "${APKTOOLPATH}" ]
then
  apktool b ./dot2smali/output/smali/${APKNAME} -o ./shareIO/${APKNAME}_unsigned.apk
else
  ${APKTOOLPATH}apktool b ./dot2smali/output/smali/${APKNAME}  ./shareIO/${APKNAME}_unsigned.apk
fi
java -jar ./dot2smali/tools/apktool-install-linux-r05-ibot/signapk.jar  ./dot2smali/tools/apktool-install-linux-r05-ibot/platform.x509.pem ./dot2smali/tools/apktool-install-linux-r05-ibot/platform.pk8  ./shareIO/${APKNAME}_unsigned.apk ./shareIO/${APKNAME}_signed.apk
adb install ./shareIO/${APKNAME}_signed.apk

