#!/bin/sh

##step1
#todo: generate .dot folder, debag .apk file
#tool: androdd.py, apktool
#cmd:  
rm ./shareIO/classes.json
rm -rf ./dot2smali/input/dot/*
python ./dot2smali/tools/androguard-1.9/androdd.py -i ./shareIO/EDGExample.apk -o ./dot2smali/input/dot -d
rm -rf ./dot2smali/input/smali/*
./dot2smali/tools/apktool-install-linux-r05-ibot/apktool d -f ./shareIO/EDGExample.apk ./dot2smali/input/smali/EDGExample

##step2
#todo: modify .smali files with new .dot files
#tool: dot2smali
#cmd:  
javac ./dot2smali/src/test/Main.java
java ./dot2smali/bin/test/Main.class

##step3
#todo: new apk srcFolder -> unsigned apk -> signed apk -> install
#tool: apktool, signapk.jar, adb
#cmd:  
./dot2smali/tools/apktool-install-linux-r05-ibot/apktool b ./dot2smali/output/smali/EDGExample  ./shareIO/unsignedEDGExample.apk
java -jar ./dot2smali/tools/apktool-install-linux-r05-ibot/signapk.jar  ./dot2smali/tools/apktool-install-linux-r05-ibot/platform.x509.pem ./dot2smali/tools/apktool-install-linux-r05-ibot/platform.pk8  ./shareIO/unsignedEDGExample.apk ./shareIO/signedEDGExample.apk
adb install ./shareIO/signedEDGExample.apk